# Generated by Django 5.1.6 on 2025-03-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dprojectapp', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
